# Generated by Django 5.2.7 on 2025-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_application_predicted_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='predicted_fit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
