# Generated by Django 5.2.7 on 2025-11-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.company'),
        ),
    ]
