# Generated by Django 5.2.7 on 2025-10-08 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_predicted_fit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'offer'], name='api_applica_user_id_f24919_idx'),
        ),
    ]
