# Generated by Django 5.2.7 on 2025-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_api_applica_user_id_f24919_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='api.skill'),
        ),
    ]
