# Generated by Django 5.2.7 on 2025-10-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_certification_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
